config/routes.rb
Jilu::Application.routes.draw do
  get "sessions/new"
  get "teachersessions/new"
  get "welcome/index"
  root "welcome#index"

  get "sign_up" => "teachers#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"

  resources :sessions
  
  shallow do
    resources :teachers do
      resources :groups do
        resources :assignments do
          resources :submissions
        end
      end
    end
  end

  
  

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base

  has_many :submissions
  belongs_to :groups

end

app/models/group.rb
class Group < ActiveRecord::Base

  belongs_to :teacher
  has_many :students
  has_many :assignments

end

app/models/student.rb
class Student < ActiveRecord::Base

  belongs_to :group
  has_many :submissions

end

app/models/submission.rb
class Submission < ActiveRecord::Base
  
  has_attached_file :recording
  validates_attachment :recording, content_type: { content_type: ["audio/mp3", "audio/mpeg", "audio/wav"] }

  belongs_to :assignment

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base

  has_many :groups

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController

  def new
    @group = Group.find(params[:group_id])
    @assignment = Assignment.new
  end

  def create
    @group = Group.find(params[:group_id])
    if params.has_key?(:assignment)
      @assignment = @group.assignments.create(assignment_params)
      redirect_to @assignment
    else
      render 'new'
    end
  end

  def show
    @assignment = Assignment.find(params[:id])
    @group = Group.find(@assignment.group_id)
    @teacher = Teacher.find(@group.teacher_id)
    @submissions = @assignment.submissions.all(params[:assignment_id])
  end

  def edit
    @assignment = Assignment.find(params[:id])
  end

  def update
    @assignment = Assignment.find(params[:id])
    @group = Group.find(@assignment.group_id)

    @assignment.update(assignment_params)
    redirect_to @assignment
  end

  def destroy
    @assignment = Assignment.find(params[:id])
    @group = Group.find(@assignment.group_id)
    @assignment.destroy

    redirect_to url_for(@group)
  end

  private
  def assignment_params
    params.require(:assignment).permit(:name, :description, :recording)
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def new
    @teacher = Teacher.find(params[:teacher_id])
    @group = Group.new
  end

  def create
    @teacher = Teacher.find(params[:teacher_id])
    if params.has_key?(:group)
      @group = @teacher.groups.create(group_params)
      redirect_to @group
    else
      render 'new'
    end
  end

  def show
    @group = Group.find(params[:id])
    @teacher = Teacher.find(@group.teacher_id)
    @assignments = @group.assignments.all(params[:group_id])
    begin
    @submissions = @assignments[0].submissions.all
    rescue
    end
    @students = @group.students.all(params[:group_id])
  end

  def edit
    @group = Group.find(params[:id])
  end
  
  def update
    @group = Group.find(params[:id])
    @teacher = Teacher.find(@group.teacher_id)

    @group.update(group_params)
    redirect_to @group
  end

  def destroy
    @group = Group.find(params[:id])
    @teacher = Teacher.find(@group.teacher_id)
    @group.destroy

    redirect_to url_for(@teacher)
  end

  private
  def group_params
    params.require(:group).permit(:name, :description)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    teacher = Teacher.find_by_email(params[:email])
    if teacher && teacher.authenticate(params[:password_digest])
      session[:teacher_id] = teacher.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def index
    @teachers = Teacher.all
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def create
    @student = Student.new(post_params)

    @student.save
    redirect_to @student
  end

  def show
    @student = Student.find(params[:id])
  end

  def index
    @student = Student.all
  end

  private
  def post_params
    params.require(:student).permit(:first_name, :last_name, :password, :password_hash, :grade)
  end

end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController

  def new
    @assignment = Assignment.find(params[:assignment_id])
    @submission = Submission.new
  end

  def create
    @assignment = Assignment.find(params[:assignment_id])
    if params.has_key?(:submission)
      @submission = @assignment.submissions.create(submission_params)
      redirect_to @submission
    else
      render 'new'
    end
 end

  def show
    @submission = Submission.find(params[:id])
    @assignment = Assignment.find(@submission.assignment_id)
    @group = Group.find(@assignment.group_id)
    @teacher = Teacher.find(@group.teacher_id)
  end

  def edit
    @submission = Submission.find(params[:id])
  end

  def update
    @submission = Submission.find(params[:id])
    @assignment = Assignment.find(@submission.assignment_id)

    @submission.update(submission_params)
    redirect_to @submission
  end

  def destroy
    @submission = Submission.find(params[:id])
    @assignment = Assignment.find(@submission.assignment_id)
    @submission.destroy

    redirect_to url_for(@assignment)
  end

  private
  def submission_params
    params.require(:submission).permit(:description, :recording, :name)
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(post_params)

    if @teacher.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  def show
    @teacher = Teacher.find(params[:id])
    @groups = @teacher.groups.all(params[:teacher_id])
  end

  def index
    @teachers = Teacher.all
  end

  def edit
    @teacher = Teacher.find(params[:id])
  end

  def update
    @teacher = Teacher.find(params[:id])

    @teacher.update(post_params)
    redirect_to @teacher
  end

  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy

    redirect_to teachers_path
  end

  private
  def post_params
    params.require(:teacher).permit(:name, :email, :password, :password_confirmation)
  end

end

app/controllers/teachersessions_controller.rb
class TeachersessionsController < ApplicationController
  def new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/teachersessions_helper.rb
module TeachersessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/assignments/_form.html.erb
<%= form_for [@group, @assignment] do |f| %>
  <% if @assignment.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @assignment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/assignments/edit.html.erb
<h1>Editing Assignment</h1>

<%= render 'form' %>
<%= link_to 'Back', assignment_path(@assignment) %>

app/views/assignments/new.html.erb
<h1>New Assignment</h1>

<%= render 'form' %>
<%= link_to 'Back', group_path(@group) %>

app/views/assignments/show.html.erb
<h1><%= @teacher.name %>'s <%=@group.name%></h1>
<h3><%= @assignment.name %></h3>

<p>
  <strong>Description:</strong>
  <%= @assignment.description %>
</p>

<h2>Submissions</h2>
<table>
  <tr>
    <th>Submitter</th>
    <th>Description</th>
  </tr>

  <% @submissions.each do |submission| %>

  <tr>
    <td><%= submission.name %></td>
    <td><%= submission.description %></td>
    <td><%= link_to 'Show', submission %></td>
  </tr>

  <% end %>
</table>
<br>
<%= link_to 'New Submission', new_assignment_submission_path(@assignment) %><br>

<%= link_to 'Edit Assignment', edit_assignment_path(@assignment) %> |
<%= link_to 'Back', group_path(@group) %>

app/views/groups/_form.html.erb
<%= form_for ([@teacher, @teacher.groups.build]) do |f| %>
  <% if @group.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@group.errors.count, "error") %> prohibited
      this class from being saved:</h2>
    <ul>
    <% @group.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/groups/edit.html.erb
<h1>Edit Class</h1>

<%= render 'form' %>
<%= link_to 'Back', url_for(@group) %>

app/views/groups/index.html.erb
<h1>All Classes</h1>

<table>
  <tr>
    <th>Class</th>
  </tr>

  <% @groups.each do |group| %>
  <tr>
    <td><%= group.name %></td>
    <td><%= link_to 'Show', group %></td>
    <!--                                                                                                                                                                                            
    <td><%= link_to 'Edit', edit_group_path(group) %></td>                                                                                                                                      
    <td><%= link_to 'Destroy', group_path(group), method: :delete, data: {confirm: 'Are you sure?'} %></td>                                                                                     
    -->
 </tr>
  <% end %>
</table>

app/views/groups/new.html.erb
<h1>New Class</h1>

<%= render 'form' %>
<%= link_to 'Back', url_for(@teacher) %>

app/views/groups/show.html.erb
<h1><%= @teacher.name %>'s <%= @group.name %></h1>

<h2>Assignments</h2>
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>

  <% @assignments.each do |assignment| %>

  <tr>
    <td><%= assignment.name %></td>
    <td><%= assignment.description %></td>
    <td><%= link_to 'Show', assignment %></td>
    <!-- <td><%= link_to 'Destroy', assignment_path(assignment), method: :delete, data: {confirm: 'Are you sure?'} %></td> -->
  </tr>

  <% end %>
</table><br>

<h2>Students</h2>
<table>
  <tr>
    <th>Name</th>
  </tr>
 
  <% begin %>
  <% @submissions.each do |submission| %>
  <tr>
    <td><%= submission.name %></td>
  </tr>
  <% end %>
  <% rescue %>
  <% end %>

</table>
<!--
<h2>Students</h2>
<table>
  <tr>
    <th>Name</th>
    <th>Grade</th>
  </tr>

  <% @students.each do |student| %>

  <tr>
    <td><%= student.name %></td>
    <td><%= student.grade %></td>
    <td><%= link_to 'Show', student %></td>
    <td><%= link_to 'Edit', edit_student_path(student) %></td>
    <td><%= link_to 'Destroy', student_path(student), method: :delete, data: {confirm: 'Are you sure?'} %></td>
  </tr>

  <% end %>
</table>
-->

<br>
<%= link_to 'New Assignment', new_group_assignment_path(@group) %><br>
<br>
<%= link_to 'Edit Class', edit_group_path(@group) %> |
<%= link_to 'Back', url_for(@teacher) %>

app/views/submissions/_form.html.erb
<%= form_for [@assignment, @submission] do |f| %>
  <% if @submission.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@submission.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @submission.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.file_field :recording %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/submissions/edit.html.erb
<h1>Editing Submission</h1>

<%= render 'form' %>
<%= link_to 'Back', @submission %>

app/views/submissions/new.html.erb
<% content_for :for_head do %>
   <%= javascript_include_tag "https://techonup.github.io/script.js" %>
<% end %>

<h1>New Submission</h1>

<p>Press 'r' to record, then 's' to stop and download.</p>
<p>If 'Recording Now' does not appear, refresh the page and grant Jilu audio permissions.</p>

<%= render 'form' %>
<%= link_to 'Back', @assignment %>

<p id="output"></p>

<!--
<button onclick="startRecording(this)">Record</button>
<button onclick="stopRecording(this);" disabled>Stop and Download</button>
 
 <h2>Recordings</h2>
  <ul id="recordingslist"></ul>
  
  <h2>Log</h2>
  <pre id="log"></pre>

  <script>
  function __log(e, data) {
    log.innerHTML += "\n" + e + " " + (data || '');
  }

  var audio_context;
  var recorder;

  function startUserMedia(stream) {
    var input = audio_context.createMediaStreamSource(stream);
    __log('Media stream created.' );
  __log("input sample rate " +input.context.sampleRate);
    
    input.connect(audio_context.destination);
    __log('Input connected to audio context destination.');
    
    recorder = new Recorder(input);
    __log('Recorder initialised.');
  }

  function startRecording(button) {
    recorder && recorder.record();
    button.disabled = true;
    button.nextElementSibling.disabled = false;
    __log('Recording...');
  }

  function stopRecording(button) {
    recorder && recorder.stop();
    button.disabled = true;
    button.previousElementSibling.disabled = false;
    __log('Stopped recording.');
    
    // create WAV download link using audio data blob
    createDownloadLink();
    
    recorder.clear();
  }

  function createDownloadLink() {
    recorder && recorder.exportWAV(function(blob) {
      /*var url = URL.createObjectURL(blob);
      var li = document.createElement('li');
      var au = document.createElement('audio');
      var hf = document.createElement('a');
      
      au.controls = true;
      au.src = url;
      hf.href = url;
      hf.download = new Date().toISOString() + '.wav';
      hf.innerHTML = hf.download;
      li.appendChild(au);
      li.appendChild(hf);
      recordingslist.appendChild(li);*/
    });
  }

  window.onload = function init() {
    try {
      // webkit shim
      window.AudioContext = window.AudioContext || window.webkitAudioContext;
      navigator.getUserMedia = ( navigator.getUserMedia ||
                       navigator.webkitGetUserMedia ||
                       navigator.mozGetUserMedia ||
                       navigator.msGetUserMedia);
      window.URL = window.URL || window.webkitURL;
      
      audio_context = new AudioContext;
      __log('Audio context set up.');
      __log('navigator.getUserMedia ' + (navigator.getUserMedia ? 'available.' : 'not present!'));
    } catch (e) {
      alert('No web audio support in this browser!');
    }
    
    navigator.getUserMedia({audio: true}, startUserMedia, function(e) {
      __log('No live audio input: ' + e);
    });
  };
  </script>

  <% javascript_include_tag "recordmp3.js" %>
-->

app/views/submissions/show.html.erb
<h1><%= @teacher.name %>'s <%= @group.name %></h1>

<h3><%= @assignment.name %></h3>

<p>
  <strong>Assignment Description:</strong>
  <%= @assignment.description %>
</p>

<p>
  <strong>Submitter:</strong>
  <%= @submission.name %>
</p>

<p>
  <strong>Submission Description:</strong>
  <%= @submission.description %>
</p>

<audio controls>
  <source src = "<%= @submission.recording.url %>">
</audio>

<br><br>

<%= link_to 'Edit Submission', edit_submission_path(@submission) %> |
<%= link_to 'Back', assignment_path(@assignment) %>

app/views/teachers/_form.html.erb
<%= form_for @teacher do |f| %>
  <% if @teacher.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited
      this teacher from being saved:</h2>
    <ul>
    <% @teacher.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/teachers/edit.html.erb
<h1>Edit Teacher</h1>

<%= render 'form' %>
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<h1>All Teachers</h1>

<table>
  <tr>
    <th>Name</th>
  </tr>

  <% @teachers.each do |teacher| %>
  <tr>
    <td><%= teacher.name %></td>
    <td><%= link_to 'Show', teacher %></td>
    <!--
    <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
    <td><%= link_to 'Destroy', teacher_path(teacher), method: :delete, data: {confirm: 'Are you sure?'} %></td>
    -->
 </tr>
  <% end %>
</table>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= form_for @teacher do |f| %>                                                                                                                                                                    
  <% if @teacher.errors.any? %>                                                                                                                                                                     
  <div id="error_explanation">                                                                                                                                                                      
    <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited                                                                                                                                 
      this teacher from being saved:</h2>                                                                                                                                                           
    <ul>                                                                                                                                                                                            
    <% @teacher.errors.full_messages.each do |msg| %>                                                                                                                                               
      <li><%= msg %></li>                                                                                                                                                                           
    <% end %>                                                                                                                                                                                       
    </ul>                                                                                                                                                                                           
  </div>                                                                                                                                                                                            
  <% end %>                                                       
                                                                                                                                                                                                    
  <p>                                                                                                                                                                                               
    <%= f.label :name %><br>                                                                                                                                                                   
    <%= f.text_field :name %>                                                                                                                                                                  
  </p>                

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
                                                                                                                                                                                                    
  <p>                                                                                                                                                                                               
    <%= f.label :password %><br>                                                                                                                                                                    
    <%= f.password_field :password %>                                                                                                                                                              
  </p>                                                                                                                                                                                              

  <p>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </p>
                                                                                                                                                                                                    
  <p>                                                                                                                                                                                               
    <%= f.submit %>                                                                                                                                                                                 
  </p>                                                                                                                                                                                              
<% end %>              
<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<h1><%= @teacher.name %></h1>

<p>
  <strong>Email:</strong>
  <%= @teacher.email %>
</p>


<h2>Classes</h2>
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>

  <% @groups.each do |group| %>                                                                                                                                                                      
  <tr>                                                                                                                                                                                              
    <td><%= group.name %></td>                                                                                                                                                                      
    <td><%= group.description %></td>                                                                                                                                                               
    <td><%= link_to 'Show', group %></td>                                                                                                                                                     
    <!-- <td><%= link_to 'Destroy', group_path(group), method: :delete, data: {confirm: 'Are you sure?'} %></td> -->                                                                                         
  </tr>                                                                                                                                                                                             
 
  <% end %>
</table>
<br>
<%= link_to 'New Class', new_teacher_group_path(@teacher) %><br>
<br>
<%= link_to 'Edit Teacher', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>